### ISSUE TITLE
Missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by ntsigilis** [hyunsooseol/snowIRT#1]
Dear Author,

Thank you for the add on Rasch analysis with jamovi (1.6.3). I am trying to test the snowIRT. When I open the snowIRT (dichotomous) and enter the dichotomous variables I get an error message "Missing value where TRUE/FALSE needed", even though there are no missing values. How do I proceed with the analysis?

Thanks a lot,

Nikolaos Tsigilis

**Comment by hyunsooseol** [comment]
Could you send  me a .omv  file to  see  if  what  happens ?  Thanks



------------------------------------------
Hyunsoo Seol, Professor
Dept.of.Education, Chung-Ang Univ.
c.p) 010-3294-5717 o) 820-5370
H) http://jamovi.kr[cid:storage_emulated_0__EmailTempImage_3_TempSignature_signature_FB_IMG_1583056935584_jpg_1592744711745]


-------- 원본 이메일 --------
보낸 사람: ntsigilis <notifications@github.com>
날짜: 20/9/9 오후 5:07 (GMT+09:00)
받은 사람: hyunsooseol/snowIRT <snowIRT@noreply.github.com>
참조: Subscribed <subscribed@noreply.github.com>
제목: [hyunsooseol/snowIRT] Missing value where TRUE/FALSE needed (#1)


Dear Author,

Thank you for the add on Rasch analysis with jamovi (1.6.3). I am trying to test the snowIRT. When I open the snowIRT (dichotomous) and enter the dichotomous variables I get an error message "Missing value where TRUE/FALSE needed", even though there are no missing values. How do I proceed with the analysis?

Thanks a lot,

Nikolaos Tsigilis

**Comment by hyunsooseol** [comment]
Hi

You can try it using example data where you can find it; Open>Data Library>item response theory for jamovi folder>dichotomos

Cheers

Seol


________________________

Hyunsoo Seol, Ph.D., Professor

Dept.of Education, Chung-Ang Univ.

c.p) 010-3294-5717, o) 820-5370

H) http://jamovi.kr

[cid:a9a75dc3-9865-4d6b-a019-e18c4b9092a8]


________________________________
보낸 사람: ntsigilis <notifications@github.com>
보낸 날짜: 2020년 9월 9일 수요일 오후 5:07
받는 사람: hyunsooseol/snowIRT <snowIRT@noreply.github.com>
참조: Subscribed <subscribed@noreply.github.com>
제목: [hyunsooseol/snowIRT] Missing value where TRUE/FALSE needed (#1)


Dear Author,

Thank you for the add on Rasch analysis with jamovi (1.6.3). I am trying to test the snowIRT. When I open the snowIRT (dichotomous) and enter the dichotomous variables I get an error message "Missing value where TRUE/FALSE needed", even though there are no missing values. How do I proceed with the analysis?

Thanks a lot,

Nikolaos Tsigilis

**Comment by ntsigilis** [comment]
Dear Seol,

 

Thank you for the prompt response.  I will try it and let you know.

 

Nikos

**Comment by ntsigilis** [comment]
The example data work perfect.

 

NT

**Comment by ntsigilis** [comment]
Please find attached the requested *.omv file.  Variables represent scores (1= correct, 0 = wrong) in a mathematics scale for early education students.

 

Nikos

**Comment by hyunsooseol** [comment]
Hi Nikolaos

I can't find attached file. Would you please attach file in the github?

**Comment by ntsigilis** [comment]
Please find attached the *.omv file.

[Rasch dicho Tsigilis.zip](https://github.com/hyunsooseol/snowIRT/files/5199542/Rasch.dicho.Tsigilis.zip)

**Comment by hyunsooseol** [comment]
You have to change measure type(nominal -> continuous) in the variable box. And it works. I attached omv file.
[Rasch dicho Tsigilis.zip](https://github.com/hyunsooseol/snowIRT/files/5199572/Rasch.dicho.Tsigilis.zip)

**Comment by ntsigilis** [comment]
Dear Professor,

 

I check it and it works perfectly.  Thanks a lot.

 

Nikos
