### ISSUE TITLE
QuestionAboutScoreTheResponse

### ISSUE THREAD

**Issue by ElJefito** [hyunsooseol/snowIRT#11]
Hello Soel, it's Larry Nelson here in Australia, experimenting with having Distractor Analysis take in and score raw test item responses (each item having options of 1,2,3,4) and output corresponding item scores of (0,1) for each student on each item.

The (0,1) items scores will then go into the Dichotomous Option.

"Score the response" does seem to do something (there's a pause of a couple of seconds) but I cannot find its output.

Not urgent at all, regards, thanks, Larry

**Comment by hyunsooseol** [comment]
Hi Larry

Could you attach it and send it to snow@cau.ac.kr? I will take a look at.

Best wishes
Seol

**Comment by ElJefito** [comment]
Hi Seol,

Good morning from Western Australia.

What I was think was this: I'll have students process sample test results
using Excel, preparing the results in a layout that I know jamovi will open
without problem (one row of column headers, then rows of raw item
responses).

Then, over to SnowIRT using my "TestAnalysisWithJamovi.pdf" paper.

My hope is that SnowIRT will make available corresponding (0,1) item scores
so that my students can then go on to SnowIRT's Dichotomous Analysis option
using another paper
<https://lertap5.com/Documentation/UsingRStudioAndSnowIRT.pdf> of mine.

So my question is: can SnowIRT create the (0,1) item scores?  I tried to do
it yesterday and had no luck.

I hope all is well there. My wife and I have been to S. Korea twice, both
times in transit at the airport (we used to work a lot in Thailand and at
times would travel from Bangkok to California -- we both have family there
-- Angie (aka Khin Khin Than) is from Burma -- her family fled as refugees,
some coming here, some going to the USA --we made several trips to Burma
before the most-recent coup. I am originally from Wisconsin but have also
lived in other countries).

Cheers, Larry

Larry R Nelson
Fremantle, Western Australia
Landline: +61 8 9336 5833 (takes messages)
Cell phone in Australia 0467 527 609
Other email: l ***@***.***>***@***.***
*Note*: Fremantle is in the same time zone as Hong Kong

**Comment by hyunsooseol** [comment]
Hi  Larry

Sorry fot the late reply. 
Currently, the snowIRT module does not have an automatic scoring function for 0/1. To score optional questions, you can use the Distractor analysis analysis. The scored results (0/1) will be saved in the data sheet. You can copy it and paste it in snowIRT >Dichotomous model to analyze it.

I'm glad you have a connection to Korea, and I look forward to your visit someday. Once again, thank you very much for your interest in the snowIRT module.

Best wishes
Seol

**Comment by hyunsooseol** [comment]
Hi Nelson

Thanks for your kind response. I got a Ph.D at The Ohio State Univ, Columbus, OH as you already know. ^^

Best wishes
Seol
