### ISSUE TITLE
Item Plot in MFRM

### ISSUE THREAD

**Issue by bayuknusantara** [hyunsooseol/snowIRT#12]
Hello. I am doing a many facet rasch model analysis with Jamovi. I want to see the item response curve graph for each item but the graph does not appear. Can you fix it? Thank you.

**Comment by hyunsooseol** [comment]
Hi [bayuknusantara](https://github.com/bayuknusantara)

Let me take a look at. . . I think 'Expected scores curve' and ' Item response curve' might have some problems.

Best
Seol

**Comment by hyunsooseol** [comment]
Hi Hi [bayuknusantara](https://github.com/bayuknusantara)

I found that it works within the cloud version of jamovi as shown below.
![image](https://github.com/hyunsooseol/snowIRT/assets/37318620/18c31d44-b97a-4dd1-a0f6-1a565182470d)

I think the problem might be related the following issue.
https://github.com/jamovi/jamovi/issues/1506

Best
Seol

**Comment by bayuknusantara** [comment]
Thanks for the information. I will use jamovi cloud for the time being.

Best 
Bayu

**Comment by hyunsooseol** [comment]
Hi [bayuknusantara](https://github.com/bayuknusantara)

I fixed a bug and pushed it in jamovi library now. I will let you know when it's available.

Best Regards
Seol
