### ISSUE TITLE
Break are not Unique

### ISSUE THREAD

**Issue by whisnuy** [hyunsooseol/snowIRT#13]
Dear Hyun,

I use Distractor analysis of snowIRT in Jamovi. I have problem and some warning written  "Break are not unique". is it common problem? how do I fix that? 

thank you very much

![Screenshot 2024-06-13 at 14 42 22](https://github.com/hyunsooseol/snowIRT/assets/44267108/932ef9e2-e1a9-41fb-bf8e-01266fda086f)

**Comment by hyunsooseol** [comment]
Hi

As shown below, If you don't have enough subjects and questions to divide the sample into high, medium, and low groups based on ability, you'll get an error.

![image](https://github.com/hyunsooseol/snowIRT/assets/37318620/5c116acc-8fdf-4c77-aef6-a5c57902c10e)

Best Regards
Seol
