### ISSUE TITLE
Error in Jamovi - 'from' must be a finite number

### ISSUE THREAD

**Issue by Daniel28052** [hyunsooseol/snowIRT#3]
Hi everyone,

I am new to Jamovi and trying to learn how to run IRT analyses with polytomous items. After importing my dataset to Jamovi, I get a  'from' must be a finite number error. Would you be able to help me ? I have also attached a screenshot of the error message. 

Thank you!

![Capture](https://user-images.githubusercontent.com/78465313/109382382-3a66ad80-7934-11eb-8f0d-7fe51fc0bbf7.PNG)

**Comment by hyunsooseol** [comment]
Hi

your data type should be specified as "continuous" not "nominal" type.

cheers
Seol

**Comment by Daniel28052** [comment]
Thank you!!
