### ISSUE TITLE
'Breaks are not unique' message. Could you please help

### ISSUE THREAD

**Issue by AVerdis** [hyunsooseol/snowIRT#4]
Dear Professor,
I work with distructor analysis. I have 10 multiple choice questions and the key for each question but I take a message reading " 'breaks' are not unique ". My variables are nominal. I have tried data as 1, 2, 3, 5 and also a, b, c, d, e. I wonder if you could help me. 
Best Regards,
Athanasios

**Comment by hyunsooseol** [comment]
Dear Athanasios
I can help you when I see your dataset. 
Could you attach .omv file as a zip file that causes error?

With thanks
Seol

**Comment by AVerdis** [comment]
Dear Professor,
Thank you so much for your answer. I think that the problem was with my database.  I have managed to proceed to the analysis. Again, thank you for your quick replay and for this excelent program.
Best wishes,
Athanasios
