### ISSUE TITLE
Unable to access 'pinfit' and 'poutfit' results when using the 'polytomous()' function

### ISSUE THREAD

**Issue by bhaskoro-muthohar** [hyunsooseol/snowIRT#6]
Hello,

I've been trying to use the polytomous() function from the snowIRT package in R, but I'm facing an issue when trying to access the 'pinfit' results.

Here's the code I'm using:
```
results <- polytomous(
    data = selected_df,
    vars = c("INTEGRITAS.1", "INTEGRITAS.2", "INTEGRITAS.3", "INTEGRITAS.4", "INTEGRITAS.5", "INTEGRITAS.6", "INTEGRITAS.7", "INTEGRITAS.8"),
    infit = TRUE,
    outfit = TRUE
)

```

When I run results$pinfit and results$poutfit, it doesn't return any output. However, the 'pinfit' and 'poutfit' element does appear as an 'active binding' when I inspect the results object using str(results).

I noticed that the snowIRT module is used in the jamovi software and it can produce the infit and outfit. I'm trying to replicate this in R, but facing the above issue.

![jamovi](https://github.com/hyunsooseol/snowIRT/assets/35159954/ed9527b0-4c6b-4263-a9e6-8c5c0635db28)

Could you help me understand why I'm unable to access the 'pinfit' results and how I can resolve this issue? Any guidance would be greatly appreciated.

Thank you.

**Comment by hyunsooseol** [comment]
Hi [bhaskoro-muthohar](https://github.com/bhaskoro-muthohar)

To run the syntax under R, you need to run the following codes first;

library(haven)

library(jmvReadWrite)

library(jmvconnect)

devtools::install_github("hyunsooseol/snowIRT")

Best
Seol

**Comment by bhaskoro-muthohar** [comment]
Hello Professor Seol,

Thank you for your quick response.

I've followed your instructions and installed the required packages (haven, jmvReadWrite, jmvconnect) and loaded them along with snowIRT. Unfortunately, I'm still experiencing the same issue when trying to access the 'pinfit' results. Here's the code I'm using:

```R
# Load necessary packages
library(haven)
library(jmvReadWrite)
library(jmvconnect)
library(snowIRT)

# Run polytomous function
results <- polytomous(
    data = selected_df,
    vars = c("INTEGRITAS.1", "INTEGRITAS.2", "INTEGRITAS.3", "INTEGRITAS.4", "INTEGRITAS.5", "INTEGRITAS.6", "INTEGRITAS.7", "INTEGRITAS.8"),
    infit = TRUE,
    outfit = TRUE
)

# Try to access pinfit
results$pinfit
```

When I run `results$pinfit`, it doesn't return any output. However, other elements like `results$inplot` and `results$outplot` do return outputs as expected.

Could you provide further guidance on how to resolve this issue? I appreciate your assistance.

Best,
Bhaskoro

**Comment by hyunsooseol** [comment]
Hi 
The example codes are the following;
library(jmv) 
library(haven) 
library(jmvReadWrite) 
library(jmvconnect)

devtools::install_github("hyunsooseol/snowIRT")

data = jmvReadWrite::read_omv("ir.omv")

snowIRT::polytomous(
  data = data,
  vars = vars(Hls1, Hls2, Hls3, Hls4, Hls5, Hls6, Hls7, Hls8, Hls9, Hls10, Hls11, Hls12, Hls13, Hls14, Hls15, Hls16),
  infit = TRUE,
  outfit = TRUE,
  thresh = FALSE)
  
jamovi will be updated soon with ver. 2.4. Until then, using the jamovi syntax in R can cause problems. I'll let you know when the program is updated.

Best
Seol

**Comment by bhaskoro-muthohar** [comment]
Hello Professor,

Thank you for your continued assistance. I've followed your latest instructions and used the `vars()` function when specifying the variables. Here is the code I've used:
```R
library(jmv)
library(haven)
library(jmvReadWrite)
library(jmvconnect)
library(snowIRT)

# Specify the dataframe
data = selected_df

# Run the polytomous function
results <- snowIRT::polytomous(
    data = data,
    vars = vars(INTEGRITAS.1, INTEGRITAS.2, INTEGRITAS.3, INTEGRITAS.4, INTEGRITAS.5, INTEGRITAS.6, INTEGRITAS.7, INTEGRITAS.8),
    infit = TRUE,
    outfit = TRUE,
    thresh = FALSE
)
```

However, I'm still having the same issue. Specifically, `results$pinfit` and `results$poutfit` are not returning any output, while `results$inplot` and `results$outplot` are returning the expected output.

I understand that the `snowIRT` package is undergoing changes for compatibility with the new version of jamovi, and I'm looking forward to the update. Meanwhile, is there any other workaround that I can use to get the 'pinfit' and 'poutfit' results?

I appreciate your help.

Best,

Bhaskoro

**Comment by hyunsooseol** [comment]
Hi

Why don't you get the result that you want using snowIRT or snowRMM  module not R?

Best
Seol

**Comment by bhaskoro-muthohar** [comment]
Hello Professor Seol,

Thank you for your suggestion to use the snowIRT or snowRMM modules directly in Jamovi. However, I have specific requirements that necessitate the use of R:

I am integrating this analysis as part of a larger Python script.
I need to automate the analysis, and using R is the only feasible way for me to integrate it into my Python workflow, as Jamovi does not have the capabilities required for this integration.
Given these constraints, is there a way to obtain the 'pinfit' and 'poutfit' results directly in R? If not, do you know if there will be any updates or changes in the upcoming version 2.4 of Jamovi that would enable this functionality in R?

Your assistance and insights are greatly appreciated.

Best regards,

Bhaskoro

**Comment by hyunsooseol** [comment]
Hi
In that case, you have to use R package(TAM, eRm) rather than using jamovi.
Integrating R codes running on jamovi into Python is not recommended as it can lead to various codes related problems.

Best
Seol

**Comment by bhaskoro-muthohar** [comment]
Hello Professor,

Thank you for your advice. I tried using the TAM package in R to calculate the infit and outfit statistics for the Polytomous Rasch Model as you suggested. However, I noticed that the results are not the same as the infit and outfit statistics produced by Jamovi.

Here is the R code that I used with the TAM package:
```R
mod <- TAM::tam.mml(resp = selected_df, irtmodel = "PCM")

# Calculate person fit statistics
person_fit <- TAM::tam.personfit(mod)

# Extract infit and outfit statistics for each subject
infit <- person_fit$infitPerson
outfit <- person_fit$outfitPerson

# Combine subjects, responses, infit, and outfit
# Assuming that the Subjects column is not part of selected_df and you want to add it
result <- data.frame(
    selected_df,
    infit = infit,
    outfit = outfit
)

# Display the result
print(result)
```

Could you please provide some insights on why there might be discrepancies between the results produced by the TAM package and those produced by Jamovi? Additionally, do you have any recommendations for obtaining results in R that are more closely aligned with those produced by Jamovi?

Your guidance is greatly appreciated.

Best regards,

Bhaskoro

**Comment by hyunsooseol** [comment]
Hi

Please refer to the following codes;
https://github.com/hyunsooseol/snowIRT/blob/master/R/polytomous.b.R#L157-L198

Best
Seol

**Comment by bhaskoro-muthohar** [comment]
Hello Professor,

Thank you so much for providing the link to the code. I tried implementing it and it worked perfectly! Your guidance has been invaluable in helping me integrate the analysis into my Python script through R.

I truly appreciate the time and effort you put into assisting me. Thanks again for your help.

Best regards,

Bhaskoro
